Update package

diff --git a/helm/package b/helm/package
--- a/helm/package
+++ b/helm/package
@@ -64,11 +64,11 @@ restoreValuesYaml() {
 }
 
 fail_trap() {
-  result=$?
-  if [ "$result" != "0" ]; then
-    echo "Failed to install $chart"
-  fi
-  exit $result
+	result=$?
+	if [ "$result" != "0" ]; then
+		echo "Failed to package $chart"
+	fi
+	exit $result
 }
 
 # Execution
